### ISSUE TITLE
Question: refresh method in AuthController.php

### ISSUE THREAD

**Issue by kouts** [afik-d/Vue-Laravel-SPA#1]
The ```refresh``` method inside AuthController.php has an ```auth()->refresh()``` call.
Shouldn't that be ```auth('api')->refresh()``` or is it left on purpose this way?

**Comment by AfikDeri** [comment]
@kouts You are absolutely right, I'll push a fix for it.

**Comment by AfikDeri** [comment]
https://github.com/AfikDeri/Vue-Laravel-SPA/commit/c2ce505780a32d621985988fc1700a682c28d959
