### ISSUE TITLE
token is null

### ISSUE THREAD

**Issue by carlosiv** [afik-d/Vue-Laravel-SPA#2]
i followed your steps, but i have this problem

> 
app.js:54277 Uncaught TypeError: Cannot read property 'token' of null
>

**Comment by PJijin** [comment]
I think the error because the user is not logged in. Try updating code into
```
if(store.getters.currentUser != null)
       axios.defaults.headers.common["Authorization"] = `Bearer ${store.getters.currentUser.token}`
    
```

**Comment by carlosiv** [comment]
thanks. this one is solved.

from the latest update
` if (store.getters.currentUser) {
        setAuthorization(store.getters.currentUser.token);
    }
}

export function setAuthorization(token) {
    axios.defaults.headers.common["Authorization"] = Bearer ${token}
}`

and there is a typo error here
`axios.interceptors.response.use(null, (error) => {
        if (error.**resposne**.status == 401) {
            store.commit('logout');
            router.push('/login');
        }`
